apiVersion: v2
name: elasticsearch
description: Elasticsearch distributed search and analytics engine

type: application
version: 1.0.0
appVersion: "8.17.0"

dependencies:
  - name: cpln-common
    version: 1.0.0
    repository: "oci://ghcr.io/controlplane-com/templates"

annotations:
  created: "2026-05-19"
  lastModified: "2026-05-19"
  category: "search"
  createsGvc: false
