apiVersion: v2
name: kafka
description: Apache Kafka event-streaming cluster in KRaft mode with optional web UI and REST proxy
type: application
version: 4.1.0
appVersion: "3.9"

dependencies:
  - name: cpln-common
    version: 1.0.0
    repository: "oci://ghcr.io/controlplane-com/templates"

annotations:
  created: "2026-07-10"
  lastModified: "2026-08-23"
  category: "event-streaming"
  createsGvc: false
