{{- include "openbao.validate" . -}}
kind: secret
name: {{ include "openbao.secret.config.name" . }}
description: OpenBao server config (HCL)
tags:
  {{- include "openbao.tags" . | nindent 4 }}
type: opaque
data:
  encoding: plain
  payload: |-
    ui = true

    listener "tcp" {
      address         = "0.0.0.0:8200"
      cluster_address = "0.0.0.0:8201"
      tls_disable     = true
    }

    storage "raft" {
      path    = "/openbao/data"
      node_id = "node-0"
    }

    api_addr     = "http://{{ include "openbao.internal.host" . }}:8200"
    cluster_addr = "http://{{ include "openbao.internal.host" . }}:8201"

    {{- if eq .Values.seal.type "static" }}

    seal "static" {
      current_key_id = "openbao-unseal-1"
      current_key    = "env://BAO_UNSEAL_KEY"
    }
    {{- else if eq .Values.seal.type "awskms" }}

    seal "awskms" {
      region     = {{ .Values.seal.aws.region | quote }}
      kms_key_id = {{ .Values.seal.aws.kmsKeyId | quote }}
    }
    {{- else if eq .Values.seal.type "gcpckms" }}

    seal "gcpckms" {
      project    = {{ .Values.seal.gcp.project | quote }}
      region     = {{ .Values.seal.gcp.region | quote }}
      key_ring   = {{ .Values.seal.gcp.keyRing | quote }}
      crypto_key = {{ .Values.seal.gcp.cryptoKey | quote }}
    }
    {{- end }}
