apiVersion: v2
name: cpln-task-runner
description: A self-hosted task queue and scheduler service similar to Google Cloud Tasks
type: application
version: 1.2.1
appVersion: "1.0.0"

dependencies:
  - name: redis
    version: 3.4.2
    repository: "oci://ghcr.io/controlplane-com/templates"
  - name: cpln-common
    version: 1.0.0
    repository: "oci://ghcr.io/controlplane-com/templates"

annotations:
  created: "2025-12-03"
  lastModified: "2026-06-26"
  category: "queue"
  createsGvc: false
