apiVersion: v2
name: nats
description: High-performance messaging with clustering, JetStream and cross-region super clusters
type: application
version: 3.0.0
appVersion: "2.11.6-alpine"

annotations:
  created: "2025-07-04"
  lastModified: "2026-08-28"
  category: "queue"
  createsGvc: false

dependencies:
  - name: cpln-common
    version: 1.0.0
    repository: "oci://ghcr.io/controlplane-com/templates"
