kind: secret
name: {{ include "mimir.secret.config.name" . }}
type: opaque
tags: {{- include "mimir.tags" . | nindent 4 }}
data:
  encoding: plain
  payload: |-
    {{- include "mimir.config" . | nindent 4 }}
