apiVersion: v2
name: cassandra
description: Cassandra cluster for Control Plane
type: application
version: 1.0.0
appVersion: "5.0"

annotations:
  created: "2026-04-21"
  lastModified: "2026-04-23"
  category: "database"
  createsGvc: false

dependencies:
  - name: cpln-common
    version: 1.0.0
    repository: "oci://ghcr.io/controlplane-com/templates"
