kafka:
  name: cluster
  image: docker.io/bitnami/kafka:3.9
  suspend: false
  replicas: 3 # must not be 2
  minReadySeconds: 60
  debug: false
  logDirs: /opt/bitnami/kafka/logs-0,/opt/bitnami/kafka/logs-1 # A comma-separated list of the directories where the log data is stored.
  volumes:
    logs:
      initialCapacity: 20 # In GB
      maxCapacity: 1000 # In GB
      performanceClass: general-purpose-ssd # general-purpose-ssd / high-throughput-ssd (Min 1000GB)
      fileSystemType: ext4 # ext4 / xfs
      minFreePercentage: 10
      snapshots:
        createFinalSnapshot: true
        retentionDuration: 7d
        schedule: 0 0 9 * * # UTC
  cpu: 2 # For millicores us 'm' like 500m
  memory: 4000Mi # Gi / Mi
  # To disable all traffic, comment out the corresponding rule. Docs: https://docs.controlplane.com/concepts/security#firewall
  firewall:
    internal_inboundAllowType: "same-gvc" # Options: same-org / same-gvc(Recommended)
    # external_inboundAllowCIDR: 0.0.0.0/0 # Provide a comma-separated list
    # external_outboundAllowCIDR: "111.222.333.444/16,111.222.444.333/32" # Provide a comma-separated list
  listeners:
    ## @param listeners.client.name Name for the Kafka client listener
    ## @param listeners.client.containerPort Port for the Kafka client listener. Except ports 9091,9093,9094
    ## @param listeners.client.protocol Security protocol for the Kafka client listener. Allowed values are 'PLAINTEXT', 'SASL_PLAINTEXT'
    ## @param listeners.client.brokersAddresses DNS address for public access to brokers. Must be the same as kafka.replicas
    client:
      containerPort: 9092 # If publicAddress is enabled, Client automatically set to port range 3000-3004
      protocol: SASL_PLAINTEXT
      name: CLIENT
      sasl:
      ## @param listeners.client.sasl.users Comma-separated list of usernames for client communications when SASL is enabled
      ## @param listeners.client.brokersAddresses Comma-separated list of passwords for client communications when SASL is enabled, must match the number of client.sasl.users
        users: "user1,user2"
        passwords: "password1,password2"
    # client2:
    #   protocol: SASL_PLAINTEXT # TLS enforced, Kafka clients should use SASL_SSL to access 'publicAddress' if provided
    #   name: CLIENT2
    #   publicAddress: kafka.example.com # Make sure Dedicate Load Balancer is enabled on the GVC
    #   # containerPort: 9095 # If publicAddress is enabled, Client automatically set to port range 3000-3004
    #   sasl:
    #   ## @param listeners.client.sasl.users Comma-separated list of usernames for client communications when SASL is enabled
    #   ## @param listeners.client.brokersAddresses Comma-separated list of passwords for client communications when SASL is enabled, must match the number of client.sasl.users
    #     users: "user1" 
    #     passwords: "password1"
  configurations:
    kafka_admin_client_port: 9092 # Ports 9093 and 9094 are Reserved for internal components
    kafka_admin_client_listener_security_protocol: SASL_PLAINTEXT # PLAINTEXT / SASL_PLAINTEXT # kafka.secrets.kafka_admin_client_passwords Must be configured
    default_replication_factor: 3 # default.replication.factor Can't be greater than the number of cluster replicas
    auto_create_topics_enable: true # auto.create.topics.enable
    log_retention_hours: 168 # The number of hours to keep a log file before deleting it (in hours)
  secrets:
    kafka_admin_client_passwords: fkor3Dro52oodA # Must be for SASL_PLAINTEXT
    kraft_cluster_id: bkdDtS1Rsf536si7BGM0JY
    inter_broker_password: HfcgCHp32e
    controller_password: ayd8iJwqXe

kafka_exporter:
  name: exporter
  image: docker.io/bitnami/kafka-exporter:1.7.0
  debug: false
  cpu: 50m
  memory: 128Mi

kafka_ui:
  name: ui
  image: provectuslabs/kafka-ui:latest
  cpu: 250m
  memory: 1Gi
  # To disable all traffic, comment out the corresponding rule. Docs: https://docs.controlplane.com/concepts/security#firewall
  firewall:
    # internal_inboundAllowType: "same-gvc" # Options: same-org / same-gvc
    external_inboundAllowCIDR: 0.0.0.0/0 # Provide a comma-separated list
    # external_outboundAllowCIDR: "111.222.333.444/16,111.222.444.333/32" # Provide a comma-separated list

kafka_client:
  name: client
  image: docker.io/bitnami/kafka:3.9
  cpu: 125m
  memory: 150Mi
  # To disable all traffic, comment out the corresponding rule. Docs: https://docs.controlplane.com/concepts/security#firewall
  # firewall:
  # internal_inboundAllowType: "same-gvc" # Options: same-org / same-gvc
  # external_inboundAllowCIDR: 0.0.0.0/0 # Provide a comma-separated list
  # external_outboundAllowCIDR: "111.222.333.444/16,111.222.444.333/32" # Provide a comma-separated list
