apiVersion: v2
name: coraza
description: Coraza web application firewall (WAF) with Tyk API Gateway for Control Plane

type: application
version: 2.0.0
appVersion: "20241018"

dependencies:
  - name: redis
    version: 3.0.2
    repository: "https://controlplane-com.github.io/helm-packages"

annotations:
  created: "2025-10-29"
  lastModified: "2025-10-29"
  category: "security"
  createsGvc: false