kind: secret
name: {{ include "mongo.secretName" . }}
description: {{ include "mongo.secretName" . }}
tags:
  {{- include "mongo.tags" . | nindent 4 }}
type: dictionary
data:
  username: {{ .Values.config.username }}
  password: {{ .Values.config.password }}
