image:
  repository: docker.io/redis:7.2

containerName: redis
port: 6379
memory: 250Mi # EX. 3000Mi = 3Gi
cpu: 200m # vCPU or milicores with; EX. 1.5 = 1500m
inheritEnv: false
capacityAI: false
firewall:
  internal_inboundAllowType: "same-org" # Options: same-org / same-gvc(Recommended)
  # external_inboundAllowCIDR: 0.0.0.0/0 # Provide a comma-separated list
  # external_outboundAllowCIDR: "0.0.0.0/0" # "111.222.333.444/16,111.222.444.333/32" # Provide a comma-separated list
supportDynamicTags: false
timeoutSeconds: 30
volumeset:
  {}
  # volume:
  #   initialCapacity: 25 # In Gigabytes. For high-throughput-ssd minimum is '1000'
  #   fileSystemType: ext4 # ext4 / xfs
  #   performanceClass: general-purpose-ssd # high-throughput-ssd / general-purpose-ssd
  # snapshots:
  #   createFinalSnapshot: "true"
  #   retentionDuration: 7d
  #   schedule: "0 1 * * *"
