kind: secret
name: {{ include "nginx.secretName" . }}
description: {{ include "nginx.secretName" . }}
tags:
  {{- include "nginx.tags" . | nindent 4 }}
type: opaque
data:
  encoding: plain
  payload: |-
{{ tpl (default "" .Values.nginxConf) . | indent 4 }}