kind: secret
name: {{ include "umami.secret.config.name" . }}
description: Umami app config
tags: {{- include "umami.tags" . | nindent 4 }}
type: dictionary
data:
  appSecret: {{ .Values.app.appSecret | quote }}
