apiVersion: v2
name: ess
description: External Secret Syncer for Control Plane
type: application
version: 1.4.0
appVersion: "v1.3.4"

annotations:
  created: "2025-03-12"
  lastModified: "2026-05-05"
  category: "secrets"
  createsGvc: false