---
kind: secret
name: {{ include "searxng.secret.settings.name" . }}
description: SearXNG settings.yml
tags: {{- include "searxng.tags" . | nindent 4 }}
type: opaque
data:
  encoding: plain
  payload: |-
{{ include "searxng.settings" . | indent 4 }}
