{{- if .Values.thanos.objectStorage.enabled }}
kind: secret
name: {{ include "prometheus.secret.objstore.name" . }}
type: opaque
tags: {{- include "prometheus.tags" . | nindent 4 }}
data:
  encoding: plain
  payload: |-
    {{- include "prometheus.objstore" . | nindent 4 }}
{{- end }}
