apiVersion: v2
name: ess
description: External Secret Syncer for Control Plane
type: application
version: 1.9.1
appVersion: v1.7.0

dependencies:
  - name: cpln-common
    version: 1.0.0
    repository: "oci://ghcr.io/controlplane-com/templates"

annotations:
  created: "2025-03-12"
  lastModified: "2026-06-26"
  category: "secrets"
  createsGvc: false