---
kind: secret
name: clickhouse-server-startup
description: Clickhouse server startup script
type: opaque
data:
  encoding: plain
  payload: |-
    #!/usr/bin/env bash
    set -euo pipefail

    # Runtime variables
    LOCATION=$(basename "${CPLN_LOCATION}")
    HOSTNAME=${HOSTNAME}
    GVC="{{ .Values.gvc.name }}"
    REPLICA_INDEX=$(echo "${HOSTNAME}" | awk -F'-' '{print $NF}')
    WORKLOAD_NAME="{{ .Release.Name }}-server"

    SELF_FQDN="replica-${REPLICA_INDEX}.${WORKLOAD_NAME}.${LOCATION}.${GVC}.cpln.local"

    echo "Starting ClickHouse server for replica ${SELF_FQDN}"

    # Ensure config directory exists
    mkdir -p /etc/clickhouse-server

    # Generate remote_servers.xml dynamically
    cat > /etc/clickhouse-server/remote_servers.xml <<EOF
    <remote_servers>
      <my_cluster>
    {{- range .Values.gvc.locations }}
      {{- $loc := .name }}
      {{- $replicas := int .replicas }}
        <shard>
        {{- range $i, $_ := until $replicas }}
          <replica>
            <host>replica-{{$i}}.{{ $.Release.Name }}-server.{{$loc}}.{{ $.Values.gvc.name }}.cpln.local</host>
            <port>9000</port>
          </replica>
        {{- end }}
        </shard>
    {{- end }}
      </my_cluster>
    </remote_servers>
    EOF

    # Generate zookeeper.xml pointing to all Keeper replicas
    cat > /etc/clickhouse-server/zookeeper.xml <<EOF
    <zookeeper>
    {{- range $i, $loc := .Values.gvc.locations }}
      {{- $replicas := int $loc.replicas }}
      {{- range $j, $_ := until $replicas }}
        <node>
          <host>replica-{{$j}}.{{ $.Release.Name }}-keeper.{{$loc.name}}.{{ $.Values.gvc.name }}.cpln.local</host>
          <port>9181</port>
        </node>
      {{- end }}
    {{- end }}
    </zookeeper>
    EOF

    echo "Sleeping for 60 seconds to let keepers come up..."
    sleep 60

    # Start ClickHouse server
    exec clickhouse-server \
      --config-file=/etc/clickhouse-server/config.xml \
      --users-file=/etc/clickhouse-server/users.xml
