---
kind: secret
name: clickhouse-database
description: clickhouse database
type: dictionary
data:
  user: {{ .Values.database.user }}
  password: {{ .Values.database.password }}
  db: {{ .Values.database.name }}
