---
kind: secret
name: {{ .Release.Name }}-clickhouse-database
description: {{ .Release.Name }}-clickhouse-database
type: dictionary
data:
  password: {{ .Values.database.password }}
  db: {{ .Values.database.name }}
