---
kind: secret
name: clickhouse-keeper-startup
description: Clickhouse keeper startup script
type: opaque
data:
  encoding: plain
  payload: |-
    #!/usr/bin/env bash
    set -euo pipefail

    # Get Control Plane runtime values
    LOCATION=$(basename "${CPLN_LOCATION}")
    HOSTNAME=${HOSTNAME}
    GVC="{{ .Values.gvc.name }}"
    REPLICA_INDEX=$(echo "${HOSTNAME}" | awk -F'-' '{print $NF}')
    WORKLOAD_NAME="{{ .Release.Name }}-keeper"

    # Construct FQDN for this replica
    SELF_FQDN="replica-${REPLICA_INDEX}.${WORKLOAD_NAME}.${LOCATION}.${GVC}.cpln.local"

    # Unique Keeper ID across locations
    KEEPER_ID="${LOCATION}-${REPLICA_INDEX}"

    echo "Starting Keeper with ID: ${KEEPER_ID}, FQDN: ${SELF_FQDN}"

    # Generate keeper config
    cat > /etc/stolon/keeper.conf <<EOF
    id = "${KEEPER_ID}"
    name = "${KEEPER_ID}"
    pgListenAddress = "0.0.0.0"
    pgPort = 5432
    dataDir = "/stolon-data"
    EOF

    echo "sleeping for 60 seconds"
    sleep 60

    # Run keeper
    exec stolon-keeper \
      --id="${KEEPER_ID}" \
      --store-backend=etcd \
      --store-endpoints="http://{{ .Release.Name }}-proxy:2379" \
      --pg-listen-address=0.0.0.0 \
      --pg-port=5432 \
      --data-dir=/stolon-data \
      --cluster-name="{{ .Release.Name }}"