---
kind: secret
name: clickhouse-server-startup
description: Clickhouse server startup script
type: opaque
data:
  encoding: plain
  payload: |-
    #!/usr/bin/env bash
    set -euo pipefail

    # Runtime variables
    LOCATION=$(basename "${CPLN_LOCATION}")
    HOSTNAME=${HOSTNAME}
    GVC="{{ .Values.gvc.name }}"
    REPLICA_INDEX=$(echo "${HOSTNAME}" | awk -F'-' '{print $NF}')
    WORKLOAD_NAME="{{ .Release.Name }}-server"

    SELF_FQDN="replica-${REPLICA_INDEX}.${WORKLOAD_NAME}.${LOCATION}.${GVC}.cpln.local"

    echo "Starting ClickHouse server for replica ${SELF_FQDN}"

    # Ensure config directory exists
    mkdir -p /etc/clickhouse-server

    # Generate remote_servers.xml dynamically
    cat > /etc/clickhouse-server/remote_servers.xml <<EOF
    <remote_servers>
      <my_cluster>
    {{- range .Values.gvc.locations }}
      {{- $loc := .name }}
      {{- $replicas := int .replicas }}
        <shard>
        {{- range $i, $_ := until $replicas }}
          <replica>
            <host>replica-{{$i}}.{{ $.Release.Name }}-server.{{$loc}}.{{ $.Values.gvc.name }}.cpln.local</host>
            <port>9000</port>
          </replica>
        {{- end }}
        </shard>
    {{- end }}
      </my_cluster>
    </remote_servers>
    EOF

    # Generate zookeeper.xml pointing to all Keeper replicas
    cat > /etc/clickhouse-server/zookeeper.xml <<EOF
    <zookeeper>
    {{- range $i, $loc := .Values.gvc.locations }}
      {{- $replicas := int $loc.replicas }}
      {{- range $j, $_ := until $replicas }}
        <node>
          <host>replica-{{$j}}.{{ $.Release.Name }}-keeper.{{$loc.name}}.{{ $.Values.gvc.name }}.cpln.local</host>
          <port>9181</port>
        </node>
      {{- end }}
    {{- end }}
    </zookeeper>
    EOF

    # Generate a minimal config.xml including users_config
    cat > /etc/clickhouse-server/config.xml <<EOF
    <clickhouse>
        <!-- Users config -->
        <users_config>/etc/clickhouse-server/users.xml</users_config>

        <!-- Logging -->
        <logger>
            <level>information</level>
            <log>/var/log/clickhouse-server/clickhouse-server.log</log>
            <errorlog>/var/log/clickhouse-server/clickhouse-server.err.log</errorlog>
        </logger>

        <!-- Ports -->
        <tcp_port>9000</tcp_port>
        <http_port>8123</http_port>

        <!-- Include generated files -->
        <include_from>/etc/clickhouse-server/remote_servers.xml</include_from>
        <include_from>/etc/clickhouse-server/zookeeper.xml</include_from>
    </clickhouse>
    EOF

    # Start ClickHouse server
    exec clickhouse-server --config-file=/etc/clickhouse-server/config.xml
