---
kind: secret
name: {{ .Release.Name }}-tidb-user
description: {{ .Release.Name }} tidb user
tags: {{- include "tidb.tags" . | nindent 4 }}
type: dictionary
data:
  rootPassword: {{ .Values.database.rootPassword }}
  user: {{ .Values.database.user }}
  password: {{ .Values.database.password }}
  db: {{ .Values.database.db }}