---
kind: secret
name: tidb-tikv-startup
description: TiDB tikv startup script
type: opaque
data:
  encoding: plain
  payload: |-
    #!/usr/bin/env bash
    set -euo pipefail

    # Runtime environment from Control Plane
    LOCATION=$(basename "${CPLN_LOCATION}")
    HOSTNAME=${HOSTNAME}
    GVC="{{ .Values.gvc.name }}"

    # Extract replica index + workload from HOSTNAME
    REPLICA_INDEX=$(echo "${HOSTNAME}" | awk -F'-' '{print $NF}')
    WORKLOAD_NAME="{{ .Release.Name }}-tikv"

    # Self FQDN for advertise
    SELF_FQDN="replica-${REPLICA_INDEX}.${WORKLOAD_NAME}.${LOCATION}.${GVC}.cpln.local"

    # Build PD endpoints (only index 0 replica per location)
    PD_ENDPOINTS=""
    LOCATIONS="{{ range .Values.gvc.locations }}{{ .name }} {{ end }}"
    for loc in $LOCATIONS; do
        endpoint="replica-0.{{ .Release.Name }}-pd.${loc}.${GVC}.cpln.local:2379"
        PD_ENDPOINTS="${PD_ENDPOINTS},${endpoint}"
    done
    PD_ENDPOINTS=${PD_ENDPOINTS#,}  # remove leading comma

    # Pick the first PD endpoint for readiness check
    PRIMARY_PD=$(echo "$PD_ENDPOINTS" | awk -F',' '{print $1}')

    echo "Generating tikv.toml for $SELF_FQDN with PD endpoints: $PD_ENDPOINTS"

    mkdir -p /etc/tikv

    cat > /etc/tikv/tikv.toml <<EOF
    [server]
    addr = "0.0.0.0:20160"
    advertise-addr = "${SELF_FQDN}:20160"
    abort-on-panic = false

    [log]
    level = "info"

    [log.file]
    filename = ""

    [storage]
    data-dir = "/data"
    reserve-space = "0GB"

    [pd]
    endpoints = ["${PD_ENDPOINTS//,/\",\"}"]

    [raftstore]
    raftdb-path = "/data/raft"

    [rocksdb]
    wal-dir = "/data/wal"
    write-buffer-size = "64MB"
    max-background-jobs = 1
    EOF

    echo "tikv.toml generated successfully at /etc/tikv/tikv.toml"

    # Wait for PD to become healthy
    echo "Waiting for PD at $PRIMARY_PD to become healthy..."
    until curl -sf "http://${PRIMARY_PD%:*}/pd/api/v1/members" | grep -q '"leader":'; do
        echo "PD cluster has no leader yet, retrying in 5s..."
        sleep 5
    done
    echo "PD leader detected, waiting additional 5s to stabilize..."
    sleep 5

    echo "PD is healthy. Starting TiKV..."
    exec /tikv-server --config /etc/tikv/tikv.toml
