---
kind: secret
name: tidb-user
description: tidb user
type: dictionary
data:
  encoding: plain
  payload: {{ .Values.database.user }}
  password: {{ .Values.database.password }}
  database: {{ .Values.database.db }}