---
kind: secret
name: {{ .Release.Name }}-tidb-tikv-startup
description: {{ .Release.Name }} TiDB tikv startup script
type: opaque
data:
  encoding: plain
  payload: |-
    #!/usr/bin/env bash
    set -euo pipefail

    LOCATION=$(basename "${CPLN_LOCATION}")
    HOSTNAME=${HOSTNAME}
    GVC="{{ .Values.gvc.name }}"
    REPLICA_INDEX=$(echo "${HOSTNAME}" | awk -F'-' '{print $NF}')
    WORKLOAD_NAME="{{ .Release.Name }}-tikv"
    SELF_FQDN="replica-${REPLICA_INDEX}.${WORKLOAD_NAME}.${LOCATION}.${GVC}.cpln.local"

    PD_ENDPOINTS=""
    LOCATIONS="{{ range .Values.gvc.locations }}{{ .name }} {{ end }}"
    for loc in $LOCATIONS; do
        endpoint="replica-0.{{ .Release.Name }}-pd.${loc}.${GVC}.cpln.local:2379"
        PD_ENDPOINTS="${PD_ENDPOINTS},${endpoint}"
    done
    PD_ENDPOINTS=${PD_ENDPOINTS#,}

    for endpoint in ${PD_ENDPOINTS//,/ }; do
        until curl -sf "http://${endpoint}/pd/health" 2>/dev/null \
              | grep -q '"health":[[:space:]]*true'; do
            echo "Waiting for PD at $endpoint..."
            sleep 5
        done
    done

    echo "PD is healthy. Starting TiKV..."

    mkdir -p /etc/tikv
    cat > /etc/tikv/tikv.toml <<EOF
    [server]
    addr = "0.0.0.0:20160"
    advertise-addr = "${SELF_FQDN}:20160"

    [log]
    level = "info"

    [storage]
    data-dir = "/data"
    reserve-space = "0GB"

    [pd]
    endpoints = ["${PD_ENDPOINTS//,/\",\"}"]

    [raftstore]
    raftdb-path = "/data/raft"

    [rocksdb]
    wal-dir = "/data/wal"
    EOF

    exec /tikv-server --config /etc/tikv/tikv.toml