gvc:
  name: tidb-gvc
  locations:
    - name: aws-us-east-2
      replicas: 2
    - name: aws-eu-central-1
      replicas: 2
    - name: aws-us-west-2
      replicas: 2
      
database:
  user: user
  password: password
  db: db