kind: secret
name: {{ .Release.Name }}-pg-config
description: {{ .Release.Name }} postgres config
tags:
  {{- include "pg.tags" . | nindent 4 }}
type: dictionary
data:
  username: {{ .Values.config.username }}
  password: {{ .Values.config.password }}