redis:
  resources:
    cpu: 200m
    memory: 256Mi
  replicas: 3 # does not apply to multi location config

sentinel:
  resources:
    cpu: 200m
    memory: 256Mi
  quorum: 2 # Keep this an even number or just 1

# Uncomment the location list below and update as you wish if you want a multi location configuration
locations:
  - aws-eu-central-1
  - azure-eastus2
  - gcp-us-east1