kind: secret
name: {{ include "redis.secretConfig.name" . }}
type: opaque
data:
  encoding: plain
  payload: |-
    bind 0.0.0.0
    protected-mode no
    save 900 1
    save 300 10
    save 60 10000
    appendonly yes
    repl-backlog-size {{ .Values.redis.replication.backlogSize }}
    repl-timeout {{ .Values.redis.replication.timeout }}
    client-output-buffer-limit slave {{ .Values.redis.replication.slaveOutputBufferLimit }}