# CHANGE THIS BEFORE COMMITTING
targetWorkload: test-app.test-gvc.cpln.local # Workload internal name of the workload to proxy traffic to

targetPort: 8080 # Port of the workload to proxy traffic to

WAFPort: 80 # Port on the WAF workload to expose to the internet

resources:
  cpu: 50m
  memory: 128Mi

multiZone: true