kind: secret
name: {{ .Release.Name }}-config
type: opaque
data:
  encoding: plain
  payload: |-
    cluster-enabled yes
    cluster-config-file nodes.conf
    cluster-node-timeout 5000
    appendonly yes
    port {{ .Values.port }}
    {{- if .Values.redis.password }}
    requirepass {{ .Values.redis.password }}
    masterauth {{ .Values.redis.password }}
    {{- end }}