gvc:
  name: clickhouse-gvc
  # Replica count will only affect the server workload
  locations:
    - name: aws-us-east-2
      replicas: 1
    - name: aws-eu-central-1
      replicas: 1
    - name: aws-us-west-2
      replicas: 1

server:
  resources:
    cpu: 1
    memory: 1Gi

keeper:
  resources:
    cpu: 1
    memory: 1Gi