apiVersion: v2
name: kafka
description: Kafka cluster app for Control Plane
type: application
version: 3.3.0
appVersion: "3.9"

annotations:
  created: "2026-02-09"
  lastModified: "2026-02-09"
  category: "event-streaming"
  createsGvc: false