---
kind: secret
name: {{ include "pgedge.secretPgcatConfig.name" . }}
description: pgCat configuration
tags: {{- include "pgedge.tags" . | nindent 2 }}
type: opaque
data:
  encoding: plain
  payload: |-
    [general]
    host = "0.0.0.0"
    port = 5432
    admin_username = "pgcat_admin"
    admin_password = "pgcat_admin"
    log_level = "info"

    [pools.{{ .Values.postgres.database }}]
    pool_mode = {{ .Values.pgcat.poolMode | quote }}
    default_pool_size = {{ .Values.pgcat.defaultPoolSize }}
    max_client_conn = {{ .Values.pgcat.maxClientConn }}
    query_parser_enabled = true
    query_parser_read_write_splitting = true

        [pools.{{ .Values.postgres.database }}.users.0]
        username = {{ .Values.postgres.username | quote }}
        password = {{ .Values.postgres.password | quote }}
        pool_size = {{ .Values.pgcat.defaultPoolSize }}

        [pools.{{ .Values.postgres.database }}.shards.0]
        database = {{ .Values.postgres.database | quote }}
        servers = [
    {{- range $locIdx, $loc := .Values.gvc.locations }}
    {{- range $i := until ($loc.replicas | int) }}
            ["replica-{{ $i }}.{{ include "pgedge.name" $ }}.{{ $loc.name }}.{{ $.Values.gvc.name }}.cpln.local", 5432, {{ if and (eq $locIdx 0) (eq $i 0) }}"primary"{{ else }}"replica"{{ end }}],
    {{- end }}
    {{- end }}
        ]
