apiVersion: v2
name: ollama
description: Ollama local LLM server with a GPU-backed API and an Open WebUI frontend

type: application
version: 1.1.1
appVersion: "0.4"

dependencies:
  - name: cpln-common
    version: 1.0.0
    repository: "oci://ghcr.io/controlplane-com/templates"

annotations:
  created: "2024-12-03"
  lastModified: "2026-08-17"
  category: "llm"
  createsGvc: false