---
kind: secret
name: {{ include "pgedge.secretConfig.name" . }}
description: pgEdge database credentials
tags: {{- include "pgedge.tags" . | nindent 2 }}
type: dictionary
data:
  username: {{ .Values.postgres.username | quote }}
  password: {{ .Values.postgres.password | quote }}
  database: {{ .Values.postgres.database | quote }}
{{- if eq .Values.backup.provider "aws" }}
  backup-bucket: {{ .Values.backup.aws.bucket | quote }}
  aws-region: {{ .Values.backup.aws.region | quote }}
{{- end }}
{{- if eq .Values.backup.provider "gcp" }}
  backup-bucket: {{ .Values.backup.gcp.bucket | quote }}
{{- end }}
