---
kind: secret
name: {{ include "pgedge.secretConfig.name" . }}
description: pgEdge database credentials
tags: {{- include "pgedge.tags" . | nindent 2 }}
type: dictionary
data:
  username: {{ .Values.postgres.username | quote }}
  password: {{ .Values.postgres.password | quote }}
  database: {{ .Values.postgres.database | quote }}
