apiVersion: v2
name: kafka
description: Kafka cluster app for Control Plane
type: application
version: 4.0.0
appVersion: "3.9"

dependencies:
  - name: cpln-common
    version: 1.0.0
    repository: "oci://ghcr.io/controlplane-com/templates"

annotations:
  created: "2026-04-28"
  lastModified: "2026-04-28"
  category: "event-streaming"
  createsGvc: false