apiVersion: v2
name: infisical
description: Infisical open-source secrets-management platform — store, version and serve app secrets via UI and API
type: application
version: 1.1.0
appVersion: "0.162.14"

annotations:
  created: "2026-07-28"
  lastModified: "2026-08-20"
  category: "secrets-management"
  createsGvc: false

dependencies:
  - name: cpln-common
    version: 1.0.0
    repository: "oci://ghcr.io/controlplane-com/templates"
  - name: postgres
    version: 3.4.1
    repository: "oci://ghcr.io/controlplane-com/templates"
  - name: redis
    version: 3.4.3
    repository: "oci://ghcr.io/controlplane-com/templates"
