kind: secret
name: {{ include "wp.secretName" . }}
description: {{ include "wp.secretName" . }}
tags:
  {{- include "wp.tags" . | nindent 4 }}
type: dictionary
data:
  MYSQL_DATABASE: {{ .Values.config.db }}
  MYSQL_ROOT_PASSWORD: {{ .Values.config.rootPassword }}
  MYSQL_USER: {{ .Values.config.rootPassword }}
  MYSQL_PASSWORD: {{ .Values.config.rootPassword }}