apiVersion: v2
name: cockroach
description: CockroachDB for Control Plane

type: application
version: 1.0.0
appVersion: "25.3.0"

annotations:
  created: "2025-08-25"
  lastModified: "2025-08-25"
  category: "database"
  createsGvc: true