gvc:
  name: cockroach-gvc
  locations:
    - name: aws-us-east-1
      replicas: 2
    - name: aws-us-west-2
      replicas: 2
    - name: gcp-us-east1
      replicas: 2

resources:
  cpu: 2000m
  memory: 4096Mi

database:
  name: mydb
  user: myuser

cockroach_defaults:
  workload_name: cockroach
  sql_port: 26257
  http_port: 8080

internal_access:
  type: same-gvc # options: same-gvc, same-org, workload-list
  workloads:  # Note: can only be used if type is same-gvc or workload-list
  # format: //gvc/GVC_NAME/workload/WORKLOAD_NAME (list workloads as an array)