kind: secret
name: {{ .Values.name }}-default-config
description: {{ .Values.name }} default config
type: opaque
data:
  encoding: plain
  payload: |-
    cluster-enabled yes
    cluster-config-file nodes.conf
    cluster-node-timeout 5000
    appendonly yes
    port {{ .Values.port }}