# Organization configuration
org:
  name: doron-test1

# NATS default configuration
nats:
  # The workload name that will be used across all GVCs
  workloadName: nats1

  # NATS container image
  image: nats

  # NATS box container image
  natsBoxImage: natsio/nats-box

  defaults:
    port: 4222
    allowNonTls: true
    cluster:
      listen: "0.0.0.0:6222"
      port: 6222 # Added explicit port for cluster
      noAdvertise: true
    gateway:
      listen: "0.0.0.0:7522"
      port: 7522
    # WebSocket configuration (disabled by default)
    websocket:
      enabled: true
      port: 8080
      compression: false
      noTls: true  # Control Plane handles TLS termination
      # allowedOrigins: []  # Uncomment and add origins if needed
      # advertise: "ws://example.com:8080"  # Uncomment if different from default
      # tls:  # Uncomment for WebSocket TLS (when not using Control Plane TLS termination)
      #   certFile: "/path/to/cert.pem"
      #   keyFile: "/path/to/key.pem"
      #   caFile: "/path/to/ca.pem"

# Define all GVCs (locations) with both GVC definition and NATS configuration
gvcs:
  - name: aws-us-west-2
    description: AWS US West (Oregon)
    tags: {}
    loadBalancer:
      dedicated: false
      trustedProxies: 0
    locationLinks:
      - //location/aws-us-west-2
    nats:
      cluster: {}
      gateway: {}
      # Example: Enable WebSocket for this specific GVC
      # websocket:
      #   enabled: true
      #   port: 8080
      #   noTls: true  # Control Plane handles TLS
      #   allowedOrigins:
      #     - "https://app.example.com"
      #     - "http://localhost:3000"
      resources:
        cpu: 500m
        memory: 256Mi
      natsBox:
        resources:
          cpu: 500m
          memory: 512Mi
      multiZone: false
      loadBalancer:
        enabled: false
        ports: []

  - name: aws-us-east-2
    description: AWS US East (Ohio)
    tags:
      environment: production
      region: us-east-2
    loadBalancer:
      dedicated: false
      trustedProxies: 0
    locationLinks:
      - //location/aws-us-east-2
    nats:
      cluster: {}
      gateway: {}
      resources:
        cpu: 500m
        memory: 256Mi
      natsBox:
        resources:
          cpu: 500m
          memory: 512Mi
      multiZone: false
      loadBalancer:
        enabled: false
        ports: []

  - name: gcp-us-central1
    description: GCP US Central (Iowa)
    tags: {}
    loadBalancer:
      dedicated: false
      trustedProxies: 0
    locationLinks:
      - //location/gcp-us-central1
    nats:
      gateway:
        extraGateways:
          - name: external-gateway
            urls:
              - "nats://external.example.com:7522"
      # Example: Enable WebSocket with custom configuration
      # websocket:
      #   enabled: true
      #   port: 8443
      #   compression: false
      #   noTls: false  # If you want NATS to handle TLS directly
      #   advertise: "wss://nats-central.example.com:8443"
      #   tls:
      #     certFile: "/etc/nats/certs/server.crt"
      #     keyFile: "/etc/nats/certs/server.key"
      resources:
        cpu: 500m
        memory: 256Mi
      natsBox:
        resources:
          cpu: 500m
          memory: 512Mi
      multiZone: false
      loadBalancer:
        enabled: false
        ports: []

  # New GVC for Middle East region
  - name: gcp-me-west1
    description: GCP Middle East West 1 (Tel Aviv)
    tags: {}
    loadBalancer:
      dedicated: false
      trustedProxies: 0
    locationLinks:
      - //location/gcp-me-west1
    nats:
      cluster: {}
      gateway: {}
      resources:
        cpu: 500m
        memory: 256Mi
      natsBox:
        resources:
          cpu: 500m
          memory: 512Mi
      multiZone: false
      loadBalancer:
        enabled: false
        ports: []