{{- include "pg-ml.validate" . -}}
kind: secret
name: {{ include "pg-ml.secretDatabase.name" . }}
description: PostgreSQL multi-location database credentials
tags:
  {{- include "pg-ml.tags" . | nindent 2 }}
type: dictionary
data:
  username: {{ .Values.postgres.username | quote }}
  password: {{ .Values.postgres.password | quote }}
  database: {{ .Values.postgres.database | quote }}
