{{- if .Values.redpanda_console.enabled }}
{{- $adminUser := index .Values.redpanda.auth.users 0 }}
kind: secret
name: {{ include "redpanda.name" . }}-console-config
type: opaque
data:
  encoding: plain
  payload: |
    kafka:
      brokers:
        - {{ include "redpanda.clusterName" . }}:{{ .Values.redpanda.listeners.kafka.internal.port }}
      sasl:
        enabled: true
        mechanism: {{ .Values.redpanda.auth.saslMechanism }}
        username: {{ $adminUser.username }}
        password: $(REDPANDA_CONSOLE_PASSWORD)
    redpanda:
      adminApi:
        enabled: true
        urls:
          - http://{{ include "redpanda.clusterName" . }}:{{ .Values.redpanda.listeners.adminApi.port }}
    schemaRegistry:
      enabled: true
      urls:
        - http://{{ include "redpanda.clusterName" . }}:{{ .Values.redpanda.listeners.schemaRegistry.port }}
      authentication:
        method: http_basic
        username: {{ $adminUser.username }}
        password: $(REDPANDA_CONSOLE_PASSWORD)
{{- end }}
